services:
  
  mysql-db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: "dbadmin"
      MYSQL_DATABASE: "hack"
      MYSQL_USER: "dbadmin"
      MYSQL_PASSWORD: "dbadmin"
    volumes:
      - ./my_OG.cnf:/etc/my.cnf
      - ./my_OG.cnf:/etc/mysql/my.cnf
      - ./sql-scripts:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - mynetw

  web:
    image: node:20
    # depends_on:
    #   mysql-db:
    #     condition: service_healthy
    depends_on:
      - mysql-db
      - redis
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - PORT=3000
    stdin_open: true
    tty: true
    ports:
      - 5000:3000
    networks:
      - mynetw

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - mynetw

volumes:
  db_data:

networks:
  mynetw:
    driver: bridge